---
metadata:
  pipeline_version: "1.0.0"

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    datetimelevel:
      format: "%(asctime)s [%(levelname)s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: datetimelevel
  root:
    level: DEBUG
    handlers: [console]

pipeline:
  departments:
    model:
      dir_name: "model"
      file_suffix: "model"
      scope_name: "geo"
    look:
      dir_name: "look"
      file_suffix: "look"
      scope_name: "ml"
    # rig:
    #   dir_name: "rig"
    #   file_suffix: "rig"
    #   scope_name: "rig"
