---
metadata:
  pipeline_version: "1.0.0"

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    datetimelevel:
      format: "%(asctime)s [%(levelname)s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: datetimelevel
    qt_console:
      level: DEBUG
      formatter: datetimelevel
  root:
    level: DEBUG
    handlers: [console, qt_console]

pipeline:
  departments:
    model:
      dir_name: "model"
      scope_name: "geo"
      format: "usdc"
    look:
      dir_name: "look"
      scope_name: "ml"
      format: "usda"
    rig:
      dir_name: "rig"
      scope_name: "rig"
      format: "usdc"
